site_name: Flight Dynamics Book Companion Website
site_url: https://agodemar.github.io/Flight_Dynamics_Book_Companion
site_description: Online companion to the book "Flight Dynamics - Theory and Practice" by ADM
repo_url: https://github.com/agodemar/Flight_Dynamics_Book_Companion
repo_name: Flight_Dynamics_Book_Companion

nav:
  - Home: index.md
  - Chapter_01: 
    - Chapter_01: Chapter_01/00_aircraft_orientation.ipynb
  - About: about.md

plugins:
  - mkdocs-jupyter

theme: readthedocs
